## Preprocessing

In [293]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dla-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [294]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(["EIN", "NAME"], axis = "columns");
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [295]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df_unqiue = application_df.nunique()
application_df_unqiue

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [296]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
#  YOUR CODE GOES HERE
applicaiton_type_list = application_df["APPLICATION_TYPE"].value_counts()
applicaiton_type_list

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [297]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 200

# Converting APPLICATION_TYPE rows that are below the cutoff value into a dataframe
application_df_cutoff = pd.DataFrame(application_df['APPLICATION_TYPE'].value_counts() < cutoff_value)

# Converting application types to replace into a list
application_types_to_replace = application_df_cutoff.index[application_df_cutoff["count"] == True].tolist()

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [299]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_list = application_df["CLASSIFICATION"].value_counts()
classification_list

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [300]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_list[classification_list > 1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [301]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classification_cutoff_value = 1000

# Converting CLASSIFICATION rows that are below the cutoff value into a dataframe
classification_df_cutoff = pd.DataFrame(application_df["CLASSIFICATION"].value_counts() < classification_cutoff_value)

# Converting classifications to replace into a list
classifications_to_replace = classification_df_cutoff.index[classification_df_cutoff["count"] == True].tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [321]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_numeric = pd.get_dummies(application_df, dtype = float)
application_df_numeric

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [322]:
# Split our preprocessed data into our features and target arrays
X = application_df_numeric.drop(columns=['IS_SUCCESSFUL'])
y = application_df_numeric['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [323]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [328]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=100, activation='relu', input_shape=(X_train.shape[1],)))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=50, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/opt/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_28"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_84 (Dense)                │ (None, 100)            │         4,400 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_85 (Dense)                │ (None, 50)             │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_86 (Dense)                │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,501 (37.11 KB)

 Trainable params: 9,501 (37.11 KB)

 Non-trainable params: 0 (0.00 B)

In [329]:
# Compile the model
nn.compile(
    optimizer='adam',        
    loss='binary_crossentropy',  
    metrics=['accuracy']         
)

In [330]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=150)

Epoch 1/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 355us/step - accuracy: 0.7130 - loss: 0.5811
Epoch 2/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.7194 - loss: 0.5639
Epoch 3/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 355us/step - accuracy: 0.7289 - loss: 0.5513
Epoch 4/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step - accuracy: 0.7402 - loss: 0.5424
Epoch 5/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 360us/step - accuracy: 0.7341 - loss: 0.5464
Epoch 6/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 522us/step - accuracy: 0.7403 - loss: 0.5426
Epoch 7/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7336 - loss: 0.5450
Epoch 8/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 365us/step - accuracy: 0.7328 - loss: 0.5447
Epoch 9/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - accuracy: 0.7421 - loss: 0.5388
Epoch 10/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - accuracy: 0.7330 - loss: 0.5453
Epoch 11/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 342us/step - accuracy: 0.7380 - loss: 0.5383
Epoch 12/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7362 - loss: 0.5410
Epoch 13/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.7394 - loss: 0.5371
Epoch 14/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - accuracy: 0.7385 - loss: 0.5404
Epoch 15/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - accuracy: 0.7369 - loss: 0.5401
Epoch 16/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 421us/step - accuracy: 0.7352 - loss: 0.5440
Epoch 17/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7338 - loss: 0.5466
Epoch 18/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7382 - loss: 0.5391
Epoch 19/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7377 - loss: 0.5371
Epoch 20/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 405us/step - accuracy: 0.7371 - loss: 0.5392
Epoch 21/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7371 - loss: 0.5406
Epoch 22/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.7396 - loss: 0.5388
Epoch 23/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7365 - loss: 0.5413
Epoch 24/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7355 - loss: 0.5392
Epoch 25/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7397 - loss: 0.5378
Epoch 26/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7397 - loss: 0.5376
Epoch 27/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7379 - loss: 0.5382
Epoch 28/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7414 - loss: 0.5387
Epoch 29/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7353 - loss: 0.5382
Epoch 30/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - accuracy: 0.7391 - loss: 0.5389
Epoch 31/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7330 - loss: 0.5452
Epoch 32/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7372 - loss: 0.5410
Epoch 33/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7382 - loss: 0.5391
Epoch 34/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7403 - loss: 0.5358
Epoch 35/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7387 - loss: 0.5371
Epoch 36/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7414 - loss: 0.5343
Epoch 37/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7419 - loss: 0.5344
Epoch 38/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7408 - loss: 0.5366
Epoch 39/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.7350 - loss: 0.5367
Epoch 40/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7423 - loss: 0.5344
Epoch 41/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - accuracy: 0.7438 - loss: 0.5338
Epoch 42/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7407 - loss: 0.5351
Epoch 43/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7362 - loss: 0.5395
Epoch 44/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7376 - loss: 0.5401
Epoch 45/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - accuracy: 0.7358 - loss: 0.5377
Epoch 46/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7380 - loss: 0.5364
Epoch 47/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7422 - loss: 0.5340
Epoch 48/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7340 - loss: 0.5404
Epoch 49/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 409us/step - accuracy: 0.7411 - loss: 0.5352
Epoch 50/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7420 - loss: 0.5332
Epoch 51/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - accuracy: 0.7401 - loss: 0.5353
Epoch 52/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7384 - loss: 0.5358
Epoch 53/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7392 - loss: 0.5369
Epoch 54/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7413 - loss: 0.5344
Epoch 55/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7402 - loss: 0.5350
Epoch 56/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7435 - loss: 0.5300
Epoch 57/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 375us/step - accuracy: 0.7390 - loss: 0.5380
Epoch 58/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 364us/step - accuracy: 0.7386 - loss: 0.5350
Epoch 59/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7419 - loss: 0.5327
Epoch 60/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7395 - loss: 0.5353
Epoch 61/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7407 - loss: 0.5303
Epoch 62/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7404 - loss: 0.5333
Epoch 63/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7362 - loss: 0.5396
Epoch 64/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7407 - loss: 0.5364
Epoch 65/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7350 - loss: 0.5414
Epoch 66/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 404us/step - accuracy: 0.7432 - loss: 0.5341
Epoch 67/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7458 - loss: 0.5271
Epoch 68/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7385 - loss: 0.5349
Epoch 69/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7406 - loss: 0.5341
Epoch 70/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7449 - loss: 0.5267
Epoch 71/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7396 - loss: 0.5329
Epoch 72/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7351 - loss: 0.5368
Epoch 73/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7399 - loss: 0.5335
Epoch 74/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7448 - loss: 0.5293
Epoch 75/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.7389 - loss: 0.5358
Epoch 76/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7402 - loss: 0.5347
Epoch 77/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7386 - loss: 0.5351
Epoch 78/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7400 - loss: 0.5335
Epoch 79/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7371 - loss: 0.5396
Epoch 80/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7417 - loss: 0.5336
Epoch 81/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7380 - loss: 0.5317
Epoch 82/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7395 - loss: 0.5351
Epoch 83/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 388us/step - accuracy: 0.7420 - loss: 0.5277
Epoch 84/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.7445 - loss: 0.5294
Epoch 85/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7413 - loss: 0.5319
Epoch 86/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - accuracy: 0.7401 - loss: 0.5362
Epoch 87/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - accuracy: 0.7414 - loss: 0.5320
Epoch 88/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7390 - loss: 0.5327
Epoch 89/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7369 - loss: 0.5384
Epoch 90/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7398 - loss: 0.5353
Epoch 91/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7422 - loss: 0.5323
Epoch 92/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7397 - loss: 0.5338
Epoch 93/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 401us/step - accuracy: 0.7398 - loss: 0.5318
Epoch 94/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7427 - loss: 0.5285
Epoch 95/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - accuracy: 0.7393 - loss: 0.5351
Epoch 96/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - accuracy: 0.7359 - loss: 0.5378
Epoch 97/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - accuracy: 0.7402 - loss: 0.5329
Epoch 98/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7430 - loss: 0.5298
Epoch 99/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7380 - loss: 0.5360
Epoch 100/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 403us/step - accuracy: 0.7415 - loss: 0.5315
Epoch 101/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7393 - loss: 0.5364
Epoch 102/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.7437 - loss: 0.5300
Epoch 103/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7389 - loss: 0.5358
Epoch 104/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7422 - loss: 0.5313
Epoch 105/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7411 - loss: 0.5335
Epoch 106/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.7402 - loss: 0.5328
Epoch 107/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7367 - loss: 0.5354
Epoch 108/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7448 - loss: 0.5297
Epoch 109/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 343us/step - accuracy: 0.7403 - loss: 0.5349
Epoch 110/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.7399 - loss: 0.5296
Epoch 111/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7436 - loss: 0.5285
Epoch 112/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7412 - loss: 0.5325
Epoch 113/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7404 - loss: 0.5349
Epoch 114/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 349us/step - accuracy: 0.7365 - loss: 0.5353
Epoch 115/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7393 - loss: 0.5347
Epoch 116/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7412 - loss: 0.5301
Epoch 117/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.7387 - loss: 0.5328
Epoch 118/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7408 - loss: 0.5348
Epoch 119/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 352us/step - accuracy: 0.7429 - loss: 0.5322
Epoch 120/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7448 - loss: 0.5261
Epoch 121/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7434 - loss: 0.5300
Epoch 122/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7374 - loss: 0.5358
Epoch 123/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7428 - loss: 0.5308
Epoch 124/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7419 - loss: 0.5339
Epoch 125/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.7421 - loss: 0.5318
Epoch 126/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7405 - loss: 0.5341
Epoch 127/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7406 - loss: 0.5324
Epoch 128/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 354us/step - accuracy: 0.7431 - loss: 0.5267
Epoch 129/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7397 - loss: 0.5330
Epoch 130/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7423 - loss: 0.5312
Epoch 131/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7412 - loss: 0.5294
Epoch 132/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 408us/step - accuracy: 0.7431 - loss: 0.5295
Epoch 133/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7436 - loss: 0.5292
Epoch 134/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 351us/step - accuracy: 0.7447 - loss: 0.5292
Epoch 135/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7411 - loss: 0.5300
Epoch 136/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7427 - loss: 0.5301
Epoch 137/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7461 - loss: 0.5275
Epoch 138/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7425 - loss: 0.5300
Epoch 139/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7406 - loss: 0.5336
Epoch 140/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.7422 - loss: 0.5314
Epoch 141/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 346us/step - accuracy: 0.7460 - loss: 0.5270
Epoch 142/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7411 - loss: 0.5320
Epoch 143/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7411 - loss: 0.5338
Epoch 144/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 345us/step - accuracy: 0.7431 - loss: 0.5305
Epoch 145/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7440 - loss: 0.5301
Epoch 146/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 347us/step - accuracy: 0.7386 - loss: 0.5313
Epoch 147/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - accuracy: 0.7432 - loss: 0.5266
Epoch 148/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7424 - loss: 0.5287
Epoch 149/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 348us/step - accuracy: 0.7386 - loss: 0.5361
Epoch 150/150
858/858 ━━━━━━━━━━━━━━━━━━━━ 0s 344us/step - accuracy: 0.7416 - loss: 0.5308

In [331]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - 563us/step - accuracy: 0.7271 - loss: 0.5849
Loss: 0.5849172472953796, Accuracy: 0.7271137237548828

In [332]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity_Optimisation.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.